version: "3"
services:
  app:
    build:
      context: ../compute/express
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongo
    environment:
      - MONGO_URI=${MONGO_URI} #mongodb://mongo:27017/resume
    networks:
      - app-network

  # mongo:
  #   image: mongo:6.0
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network

  frontend:
    build:
      context: ../website/angular
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
