# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bleedcopper
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: cloudresume
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ViewCounter

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-2
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
          Resource: "arn:aws:dynamodb:${aws.region}:${aws:accountId}:table/viewcount"

plugins:
  - serverless-offline

functions:
  viewCounter:
    handler: handler.viewCounter
    events:
      - httpApi:
          path: /
          method: get
