name: AWS

on:
    push:
        branches: [ master ]
 
env:
  AWS_ROLE_TO_ASSUME: 'arn:aws:iam::724772065639:role/GithubTerraform'
  SLS_ROLE_TO_ASSUME: 'arn:aws:iam::724772065639:role/SFRole-8ccd82'
  AWS_S3_BUCKET: 'aws.rissaquindoza.com'
  
permissions:
  id-token: write
  contents: read
jobs:
  changes:
        runs-on: ubuntu-latest
        outputs:
            awsLambda: ${{ steps.filter.outputs.awsLambda }}
            react: ${{ steps.filter.outputs.react }}
            terraform: ${{ steps.filter.outputs.terraform }}
            workflow: ${{ steps.filter.outputs.workflow }}
        steps:
        - uses: actions/checkout@v3
        - uses: dorny/paths-filter@v2
          id: filter
          with:
            filters: |
                awsLambda:
                    - 'compute/awsLambda/**'
                react:
                    - 'website/react/**'
                terraform:
                    - 'IaC/terraform/aws/**'
                workflow:
                    - '.github/workflows/aws.yml'
  terraform:
        needs: changes
        defaults:
            run:
                working-directory: 'IaC/terraform/aws' 
        runs-on: ubuntu-latest
        if: ${{ needs.changes.outputs.terraform == 'true' || needs.changes.outputs.workflow == 'true' }}
        steps:
            - uses: actions/checkout@v4
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
                aws-region: ap-southeast-2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
                terraform_version: 1.4.5
            - name: Setup Terraform Backend
              id: backend
              run: |
                cat > backend.config << EOF
                bucket = "rqterraformstate"
                key = "terraform.tfstate"
                region = "ap-southeast-2"
                encrypt = true
                EOF
            - name: Terraform Init
              run: terraform init -backend-config="backend.config" -upgrade
            - name: Terraform Plan
              env:
                TF_VAR_cloudflare_zoneid: ${{ secrets.TF_VAR_CLOUDFLARE_ZONEID}}
                TF_VAR_cloudflare_api: ${{ secrets.TF_VAR_CLOUDFLARE_API}}
              run: terraform plan 
            - name: Terraform apply
              env:
                TF_VAR_cloudflare_zoneid: ${{ secrets.TF_VAR_CLOUDFLARE_ZONEID}}
                TF_VAR_cloudflare_api: ${{ secrets.TF_VAR_CLOUDFLARE_API}}
              run: terraform apply -auto-approve 
              
  frontend:
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: 'website/react'
    if: ${{ always() && (needs.changes.outputs.react == 'true'  || needs.changes.outputs.workflow == 'true') }}
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './website/react/package-lock.json'
    - run: npm ci --legacy-peer-deps
    - run: npm run build 
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        aws-region: ap-southeast-2

    - name: Manual upload to S3
      run: aws s3 sync --delete out/ s3://${{ env.AWS_S3_BUCKET }}

    - name: Invalidate Cloudflare cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.TF_VAR_CLOUDFLARE_ZONEID }}/purge_cache" \
             -H "Authorization: Bearer ${{ secrets.TF_VAR_CLOUDFLARE_API }}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API }}

  backend-test:
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ always() && (needs.changes.outputs.awsLambda == 'true' || needs.changes.outputs.workflow == 'true')  }}
    defaults:
      run:
        working-directory: 'tests/unit/pytest'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest with coverage report
      run: |
        pytest -v 
        
  backend:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    needs: backend-test
    if: success('backend-test') 
    defaults:
      run:
        working-directory: 'compute/awsLambda'
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python   
      uses: actions/setup-python@v4  
      with:  
        python-version: ${{ matrix.python-version }}  
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   id: credentials
    #   with:
    #     role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
    #     aws-region: ap-southeast-2
    # - name: Serverless Deploy
    #   uses: dhollerbach/actions.serverless-with-python-requirements@v2
    #   env:
    #     STAGE: prod
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: -c "cd ./compute/awsLambda && serverless plugin install --name serverless-offline && serverless deploy --stage prod --region ap-southeast-2"
        entrypoint: /bin/sh
      env:
        # AWS_ACCESS_KEY_ID: ${{ steps.credentials.outputs.aws-access-key-id }}
        # AWS_SECRET_ACCESS_KEY: ${{ steps.credentials.outputs.aws-secret-access-key }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        
  cypress-tests:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: 'tests/cypress'
