name: Azure

on:
    push:
        branches: [ master ]

env:
  AZURE_STORAGE_NAME: 'tfcloudresumestore'
  AZURE_FUNCTIONAPP_NAME: 'tf-cloudresume-fnc'   # set this to your function app name on Azure
  DOTNET_VERSION: '8.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  
permissions:
  id-token: write
jobs:
  changes:
        runs-on: ubuntu-latest
        outputs:
            azurefnc: ${{ steps.filter.outputs.azurefnc }}
            vue: ${{ steps.filter.outputs.vue }}
            terraform: ${{ steps.filter.outputs.terraform }}
            workflow: ${{ steps.filter.outputs.workflow }}
        steps:
        - uses: actions/checkout@v3
        - uses: dorny/paths-filter@v2
          id: filter
          with:
            filters: |
                azurefnc:
                    - 'compute/azureFunctions/**'
                vue:
                    - 'website/vue/**'
                terraform:
                    - 'IaC/terraform/azure/**'
                workflow:
                    - '.github/workflows/azure.yml'
  terraform:
        needs: changes
        defaults:
            run:
                working-directory: 'IaC/terraform/azure' 
        runs-on: ubuntu-latest
        if: ${{ needs.changes.outputs.terraform == 'true' || needs.changes.outputs.workflow == 'true' }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
            - name: Setup Terraform Backend
              id: backend
              run: |
                cat > backend.config << EOF
                resource_group_name = "terraformstate"
                storage_account_name = "rqterraformstate"
                container_name = "terraformstate"
                key = "terraform.tfstate"
                use_oidc = true   
                
                client_id       = "4785bdc7-671d-4140-b6fd-589bf8ee38e4"
                tenant_id       = "b490748b-6369-41b5-8b27-eaf6200aa287"
                subscription_id = "472e404e-7704-43a8-96a1-072607c075e1"
                EOF
            - name: Terraform Init
              run: terraform init -backend-config="backend.config" -upgrade
            - name: Terraform Plan
              env:
                TF_VAR_cloudflare_zoneid: ${{ secrets.TF_VAR_CLOUDFLARE_ZONEID}}
                TF_VAR_cloudflare_api: ${{ secrets.TF_VAR_CLOUDFLARE_API}}
              run: terraform plan 
            - name: Terraform apply
              env:
                TF_VAR_cloudflare_zoneid: ${{ secrets.TF_VAR_CLOUDFLARE_ZONEID}}
                TF_VAR_cloudflare_api: ${{ secrets.TF_VAR_CLOUDFLARE_API}}
              run: terraform apply -auto-approve 
              
  frontend:
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: 'website/vue'
    if: ${{ always() && (needs.changes.outputs.vue == 'true'  || needs.changes.outputs.workflow == 'true') }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './website/vue/package-lock.json'
    - run: npm ci
    - run: npm run build 

    - name: Azure login
      uses: azure/login@v1
      with:
          client-id: "4785bdc7-671d-4140-b6fd-589bf8ee38e4"
          tenant-id: "b490748b-6369-41b5-8b27-eaf6200aa287"
          subscription-id: "472e404e-7704-43a8-96a1-072607c075e1"

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{env.AZURE_STORAGE_NAME}} --auth-mode key -d '$web' -s './website/vue/dist/' --overwrite
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()

      
    - name: Invalidate Cloudflare cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.TF_VAR_CLOUDFLARE_ZONEID }}/purge_cache" \
             -H "Authorization: Bearer ${{ secrets.TF_VAR_CLOUDFLARE_API }}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API }}

  backend:
   runs-on: windows-latest # For Linux, use ubuntu-latest
   needs: terraform
   if: ${{ always() && (needs.changes.outputs.azurefnc == 'true' || needs.changes.outputs.workflow == 'true')  }}
   steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          client-id: "4785bdc7-671d-4140-b6fd-589bf8ee38e4"
          tenant-id: "b490748b-6369-41b5-8b27-eaf6200aa287"
          subscription-id: "472e404e-7704-43a8-96a1-072607c075e1"

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh # For Linux, use bash
      run: |
        pushd './compute/azureFunctions'
        dotnet build --configuration Release --output ./output
        popd

        
    - name: 'Run Unit Tests'
      shell: pwsh
      run: |
        pushd './tests/unit/xUnit'
        dotnet build
        dotnet test
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: 'compute/azureFunctions/output/'
       
    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
      
  playwright-tests:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tests/playwright'
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
