name: Blob storage website CI

on:
    push:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'website/vue'
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }
}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './website/vue/package-lock.json'
    - run: npm ci
    - run: npm run build 
    
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'website/vue'
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name rqcloudresumestore --auth-mode key -d '$web' -s dist/
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
